### ISSUE TITLE
如此配置后，出现了一些报错

### ISSUE THREAD

**Issue by kyle-li-dev** [AaronJny/scrapy_redis_expiredupefilter#1]
### spider
from scrapy_redis_expiredupefilter.spiders import RedisSpider
### setting
REDIS_PARAMS  = {
   'host': SECRET['redis_hostname'],
   'port': SECRET['redis_port'],
   'password': SECRET['redis_password'],
   'db': SECRET['redis_db']
}
SCHEDULER_QUEUE_CLASS = 'scrapy_redis_expiredupefilter.queue.PriorityQueue'
DUPEFILTER_CLASS = 'scrapy_redis_expiredupefilter.dupefilter.RFPDupeFilter'
SCHEDULER = 'scrapy_redis_expiredupefilter.scheduler.Scheduler'
SCHEDULER_PERSIST = True
EXTENSIONS = {
    'scrapy_redis_expiredupefilter.extensions.ExpiredFingerprintCleaner': 100,
}

## 报错内容
[twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/twisted/internet/defer.py", line 190, in maybeDeferred
    result = f(*args, **kwargs)
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/scrapy_redis_expiredupefilter/extensions.py", line 47, in clean_expired_fingerprints
    x = self.server.zremrangebyscore(self.key, 0, int(time.time()))
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/commands/core.py", line 4603, in zremrangebyscore
    return self.execute_command("ZREMRANGEBYSCORE", name, min, max)
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/client.py", line 1238, in execute_command
    return conn.retry.call_with_retry(
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/client.py", line 1239, in <lambda>
    lambda: self._send_command_parse_response(
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/client.py", line 1215, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/client.py", line 1254, in parse_response
    response = connection.read_response()
  File "/Users/？？？/opt/anaconda3/envs/spider/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
    raise response
**redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value**

**Comment by kyle-li-dev** [comment]
ummmm 大乌龙
大家用之前记得掐掉之前用的 scrapy_redis创建的 set 类型的键
